"""
Django settings for statmagic project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os,socket
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# System settings
HOST = socket.gethostname()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: don't run with debug turned on in production!

IS_MTRI_SERVER = 'apps' in HOST or 'precision' in HOST

# TODO: add condition that return true for USGS production server
IS_PRODUCTION_SERVER = 'apps' in HOST

if IS_PRODUCTION_SERVER:
    # Load production key from ENV
    SECRET_KEY = os.environ['SECRET_KEY'] 
    DEBUG = True
    DJANGO_VITE_DEV = False
else:
    SECRET_KEY = 'iat3k%kt0e53=c*68_!m-cr-tb2=r#1m6925*(5k1-d5wvhan)'#'django-insecure-horfy%^!-p6s)tda@@=iyslwunl@!0+b@hxvh)fm*f0hxpxvu-'
    DEBUG = True
    DJANGO_VITE_DEV = True

# Determines whether app is hosted at the top of the domain e.g. myserver.org
# or at a different location e.g. myserver.org/statmagic
URL_PREFIX = '/' if IS_MTRI_SERVER else '/statmagic/'


ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'django_vite',
    'cma',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'statmagic.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
             os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'statmagic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
 'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'statmagic',
        'USER': 'django_user_statmagic',
        'PASSWORD': 'gimme_gimme_gallium',#os.environ['DJANGO_USER_STATMAGIC_PGPASS'],
        'HOST' : 'per510c',
        'PORT': '5433'
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache',
        'TIMEOUT': 14400
    },
    'permanent': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache',
        'TIMEOUT': None
    }
}

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Vite configuration
DJANGO_VITE = {
    "default": {
        "dev_mode": DJANGO_VITE_DEV,
    }
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / "static" / "react" / "dist"
]
STATIC_URL = f'{URL_PREFIX}static/'
STATIC_ROOT = BASE_DIR / "assets"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MAPFILE_FILENAME = 'statmagic.map'

MAPSERVER_SERVER = 'vm-apps2'#'per440c'#'vm-apps2'

# Location on the MAPSERVER_SERVER where the sync'd data lives
TILESERVER_LOCAL_SYNC_FOLDER = '/net/vm-apps2/home/mgbillmi/statmagic/data/datalayer_download/'

    
